#!/bin/bash

if [ $# -lt 1 ]; then
	echo "tarantool.org/dist file uploader by extension."
	echo
	echo "usage: upload_to_dist_ext <ext>"
	exit 1
fi

for file in `ls -1 *.$1`; do
	upload_to_dist "$file"
done
